### ISSUE TITLE
Question: How to pass level 8?

### ISSUE THREAD

**Issue by Timofei302** [UnicornsOfDeath/continuous-factory#19]
I may not be on topic, but how to pass level 8? Is it even possible?
![Screenshot_20230719-225306](https://github.com/UnicornsOfDeath/continuous-factory/assets/59145732/d8050f73-8a07-4ba5-b6d8-6459f7ade712)

**Comment by cxong** [comment]
yes it is possible
please discuss in the TIC-80 discord https://github.com/nesbox/TIC-80#community

**Comment by Timofei302** [comment]
> yes it is possible
> please discuss in the TIC-80 discord https://github.com/nesbox/TIC-80#community

Can you take a screenshot of the solution? So that I really have no idea how to solve this.

Then I will close this issue.
