### ISSUE TITLE
Make more levels

### ISSUE THREAD

**Issue by cxong** [UnicornsOfDeath/continuous-factory#2]
Maybe 30 will do
Might need more mechanics to make this work (like a void tile?)

**Comment by Maaate** [comment]
a void tile.
maybe a teleport tile

**Comment by cxong** [comment]
The levels need to teach players tricks to prevent difficulty curve being too steep and to remove the need to give lots of instructions

- [x] folders pass through the opposite end of factories
- [x] cross intersection
- [x] can pass through factories even if not needed
- [x] use reverse belt to pass folders back through the same factory
- [x] using gates as substitutes for belts (straight through, turning, reverse)
- [x] how to use minimal amount of belts (gates at the last minute)
- [x] use gates as two turns (turn one way when it has a job, turn the other when that job is done)
- [x] jobs can block each other

**Comment by cxong** [comment]
Should wait until #8 before adding more levels
